function e0b(){}
function k0b(){}
function n0b(){}
function o0b(){o0b=yxc;j0b=new n0b}
function c0b(){dlb(this,g0b(new h0b))}
function V_b(a,b,c){Lkb.call(this,a,b,c,(V$b(),U$b))}
function B6b(a){var b;if(!a.g){b=new c0b(new e0b);a.g=b}return a.g}
function A6b(a){var b;if(!a.f){b=new V_b(Ujb(plb(a.a)),B6b(a),z6b(a));kkb((qlb(a.a),b),Blb(qlb(a.a)));a.f=b}return a.f}
function m0b(a){if(!a.a){a.a=true;yu();Bu((my(),'.GOBEEQNII span{margin-right:5px;}'));return true}return false}
function r0b(a){var b;b=new yrb;Yn(b.a,"<a href='#'>Inbox <span id='");srb(b,z$(a));Yn(b.a,tEc);return new f$(bo(b.a))}
function p0b(a){var b;b=new yrb;Yn(b.a,"<a href='#'>Deleted Items <span id='");srb(b,z$(a));Yn(b.a,tEc);return new f$(bo(b.a))}
function q0b(a){var b;b=new yrb;Yn(b.a,"12 <span id='");srb(b,z$(a));Yn(b.a,"'><\/span> <i>unread<\/i>");return new f$(bo(b.a))}
function h0b(){this.g=(new k0b,o0b(),j0b);m0b(this.g);this.e=Jq($doc);this.a=Jq($doc);this.c=Jq($doc);this.f=new d0(this.e);this.b=new d0(this.a);this.d=new d0(this.c)}
function g0b(a){var b,c,d,e,f,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D;b=new aGb;Myb(b,(c=new zBb(iEc),Myb(c,(d=new NEb,d.a=WBc,MEb(d),d)),Myb(c,(e=new dFb,Myb(e,(g=new pFb,oFb(g,(i=new wCb(3),i.b=jEc,uCb(i),i)),g)),Myb(e,(j=new gFb,Myb(j,(k=new Idb,k.Ad((n=new Zdb(p0b(a.a).a),o=f0(n.$),c0(a.b),o.b?Vp(o.b,o.a,o.c):i0(o.a),Xdb(n,new vzb((p=new yrb,Yn(p.a,'42'),new f$(bo(p.a))).a),c0(a.b)),n)),D0(k.$,sEc,true),k)),j)),Myb(e,(q=new kFb,Myb(q,(r=new Csc,TFb(r,(s=new yrb,Yn(s.a,'&lt;a href="#"&gt;Deleted Items\\n \\s\\s&lt;b:Badge&gt;42&lt;/b:Badge&gt;\\n &lt;/a&gt;'),new f$(bo(s.a))).a),D0(r.$,mEc,true),r)),q)),e)),Myb(c,(f=new dFb,Myb(f,(t=new pFb,oFb(t,(u=new wCb(3),u.b='Advanced',uCb(u),u)),t)),Myb(f,(v=new gFb,Myb(v,(w=new Idb,w.Ad((x=new Zdb(r0b(a.c).a),y=f0(x.$),c0(a.d),y.b?Vp(y.b,y.a,y.c):i0(y.a),Xdb(x,(z=new vzb(q0b(a.e).a),A=f0(z.$),c0(a.f),A.b?Vp(A.b,A.a,A.c):i0(A.a),Xdb(z,new HCb((uWb(),gRb)),c0(a.f)),z),c0(a.d)),x)),D0(w.$,sEc,true),w)),v)),Myb(f,(B=new kFb,Myb(B,(C=new Csc,TFb(C,(D=new yrb,Yn(D.a,'&lt;a href="#"&gt;Inbox\\n \\s\\s&lt;b:Badge&gt;12\\n \\s\\s\\s&lt;b:Icon type="ENVELOPE"/&gt;\\n \\s\\s\\s&lt;i&gt;unread&lt;/i&gt;\\n \\s\\s&lt;/b:Badge&gt;\\n &lt;/a&gt;'),new f$(bo(D.a))).a),D0(C.$,mEc,true),C)),B)),f)),c));return b}
var tEc="'><\/span> <\/a>",sEc='GOBEEQNII';YY(877,528,oyc,V_b);YY(880,533,pyc,c0b);YY(881,1,{},e0b);YY(882,1,{},h0b);_.a=null;_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;_.g=null;YY(883,1,{},k0b);var j0b=null;YY(884,1,{},n0b);_.a=false;YY(1057,1,Qyc);_.vb=function f9b(){Umb(this.b,A6b(this.a.a))};var JN=Opb(mDc,'BadgePresenter',877),ON=Opb(mDc,'BadgeView',880),NN=Opb(mDc,'BadgeView_BinderImpl',881),KN=Opb(mDc,'BadgeView_BinderImpl$Widgets',882),MN=Opb(mDc,'BadgeView_BinderImpl_GenBundle_default_InlineClientBundleGenerator',883),LN=Opb(mDc,'BadgeView_BinderImpl_GenBundle_default_InlineClientBundleGenerator$1',884);Xyc(Em)(2);