function w5b(){}
function z5b(){}
function C5b(){}
function F5b(){}
function K5b(){}
function N5b(){}
function Q5b(){}
function T5b(){}
function X5b(){}
function $5b(){}
function _5b(){_5b=iec;W5b=new $5b}
function u5b(){Ddb(this,H5b(new I5b))}
function l5b(a,b,c){jdb.call(this,a,b,c,(WQb(),VQb))}
function Qcc(a,b){$wnd.bootbox.alert(a,function(){b.Ee()})}
function Scc(b,c){$wnd.bootbox.prompt(b,function(a){c.Ge(a)})}
function Rcc(b,c){$wnd.bootbox.confirm(b,function(a){c.Fe(a)})}
function O7b(a){var b;if(!a.d){b=new u5b(new F5b);a.d=b}return a.d}
function Z5b(a){if(!a.a){a.a=true;qq();Uh(nq,F$c);uq();return true}return false}
function N7b(a){var b;if(!a.c){b=new l5b(scb(Pdb(a.a)),O7b(a),M7b(a));Kcb((Qdb(a.a),b),_db(Qdb(a.a)));a.c=b}return a.c}
function I5b(){this.a=new K5b;this.b=new N5b;this.c=new Q5b;this.d=new T5b;this.e=(new X5b,_5b(),W5b);Z5b(this.e)}
function H5b(a){var b,c,d,e,f,g,i,j,k,n,o,p,q,r,s,t,u,v,w,x,y,z,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z;b=new rxb;Yqb(b,(c=new pwb,c.a=znc,owb(c),c));Yqb(b,(d=new Brb,Yqb(d,(e=new cub(4),nU(e._,n$c,true),Axb(e.c,o$c),e)),Yqb(d,(f=new Rub,Qub(f,(E=new Rjb,Dj(E.a,p$c),new TR(Ij(E.a))).a),f)),Yqb(d,(g=new ixb,hxb(g,(F=new Rjb,Dj(F.a,q$c),new TR(Ij(F.a))).a),nU(g._,Gwc,true),nU(g._,Hwc,true),g)),Yqb(d,(i=new Rub,Qub(i,(G=new Rjb,Dj(G.a,r$c),new TR(Ij(G.a))).a),i)),Yqb(d,(j=new ixb,hxb(j,(H=new Rjb,Dj(H.a,s$c),new TR(Ij(H.a))).a),nU(j._,Gwc,true),nU(j._,Hwc,true),j)),Yqb(d,(k=new Rub,Qub(k,(I=new Rjb,Dj(I.a,t$c),new TR(Ij(I.a))).a),k)),Yqb(d,(n=new ixb,hxb(n,(J=new Rjb,Dj(J.a,u$c),new TR(Ij(J.a))).a),nU(n._,Gwc,true),nU(n._,_Ec,true),n)),nU(d._,v$c,true),d));Yqb(b,(o=new xwb,Yqb(o,(p=new Fwb,Ewb(p,(K=new cub(3),Axb(K.c,Xwc),K)),p)),Yqb(o,(q=new Awb,Yqb(q,(L=new Orb,Nyb(L.d,w$c),qrb(L,(UMb(),iKb)),zyb(L,KG,(Zzb(),Wzb)),rU(L,a.a,(Xq(),Xq(),Wq)),L)),q)),Yqb(o,(r=new Cwb,Yqb(r,(M=new ixb,hxb(M,(N=new Rjb,Dj(N.a,x$c),new TR(Ij(N.a))).a),nU(M._,Gwc,true),nU(M._,_Ec,true),M)),r)),o));Yqb(b,(s=new xwb,Yqb(s,(t=new Fwb,Ewb(t,(O=new cub(3),Axb(O.c,y$c),O)),t)),Yqb(s,(u=new Awb,Yqb(u,(P=new Orb,Nyb(P.d,w$c),qrb(P,iKb),zyb(P,KG,Wzb),rU(P,a.b,Wq),P)),u)),Yqb(s,(v=new Cwb,Yqb(v,(Q=new ixb,hxb(Q,(R=new Rjb,Dj(R.a,z$c),new TR(Ij(R.a))).a),nU(Q._,Gwc,true),nU(Q._,_Ec,true),Q)),v)),s));Yqb(b,(w=new xwb,Yqb(w,(x=new Fwb,Ewb(x,(S=new cub(3),Axb(S.c,A$c),S)),x)),Yqb(w,(y=new Awb,Yqb(y,(T=new Orb,Nyb(T.d,w$c),qrb(T,iKb),zyb(T,KG,Wzb),rU(T,a.c,Wq),T)),y)),Yqb(w,(z=new Cwb,Yqb(z,(U=new ixb,hxb(U,(V=new Rjb,Dj(V.a,B$c),new TR(Ij(V.a))).a),nU(U._,Gwc,true),nU(U._,_Ec,true),U)),z)),w));Yqb(b,(A=new xwb,Yqb(A,(B=new Fwb,Ewb(B,(W=new cub(3),Axb(W.c,C$c),W)),B)),Yqb(A,(C=new Awb,Yqb(C,(X=new Orb,Nyb(X.d,w$c),qrb(X,iKb),zyb(X,KG,Wzb),rU(X,a.d,Wq),X)),C)),Yqb(A,(D=new Cwb,Yqb(D,(Y=new ixb,hxb(Y,(Z=new Rjb,Dj(Z.a,D$c),new TR(Ij(Z.a))).a),nU(Y._,Gwc,true),nU(Y._,_Ec,true),Y)),D)),A));return b}
var s$c='&lt;inherits name="org.gwtbootstrap3.extras.bootbox.Bootbox"/&gt;',F$c='.GMU211BDIJ{background-color:#fcf2f2;border-color:#dfb5b4;}.GMU211BDJJ{margin-top:0 !important;}',x$c='@UiHandler("button")\\n public void handleButton(ClickEvent event) {\\n \\s\\sBootbox.alert("Hello World");\\n }',z$c='@UiHandler("button")\\n public void handleButton(ClickEvent event) {\\n \\s\\sBootbox.alert("Hello World", new AlertCallback() {\\n \\s\\s\\s\\s@Override\\n \\s\\s\\s\\spublic void callback() {\\n \\s\\s\\s\\s\\s\\sWindow.alert("Hello World Callback");\\n \\s\\s\\s\\s}\\n \\s\\s});\\n }',B$c='@UiHandler("button")\\n public void handleButton(ClickEvent event) {\\n \\s\\sBootbox.confirm("Hello World", new ConfirmCallback() {\\n \\s\\s\\s\\s@Override\\n \\s\\s\\s\\spublic void callback(boolean result) {\\n \\s\\s\\s\\s\\s\\sWindow.alert("Return: " + result);\\n \\s\\s\\s\\s}\\n \\s\\s});\\n }',D$c='@UiHandler("button")\\n public void handleButton(ClickEvent event) {\\n \\s\\sBootbox.prompt("Hello World", new PromptCallback() {\\n \\s\\s\\s\\s@Override\\n \\s\\s\\s\\spublic void callback(String result) {\\n \\s\\s\\s\\s\\s\\sWindow.alert("Return: " + result);\\n \\s\\s\\s\\s}\\n \\s\\s});\\n }',y$c='Alert with Callback',u$c='Bootbox.alert("Message");',G$c='BootboxJSPresenter',H$c='BootboxJSView',I$c='BootboxJSView$1',J$c='BootboxJSView$2',K$c='BootboxJSView$3',L$c='BootboxJSView_BinderImpl',M$c='BootboxJSView_BinderImpl$Widgets',N$c='BootboxJSView_BinderImpl$Widgets$1',O$c='BootboxJSView_BinderImpl$Widgets$2',P$c='BootboxJSView_BinderImpl$Widgets$3',Q$c='BootboxJSView_BinderImpl$Widgets$4',R$c='BootboxJSView_BinderImpl_GenBundle_default_StaticClientBundleGenerator',S$c='BootboxJSView_BinderImpl_GenBundle_default_StaticClientBundleGenerator$1',A$c='Confirm',v$c='GMU211BDIJ',n$c='GMU211BDJJ',E$c='Hello World',l$c='Hello World Callback',C$c='Prompt',m$c='Return: ',w$c='Run Example',t$c='Then, you can call static method from Bootbox class in GWT client code:',p$c='To use Bootbox, you must first add the extras module to your project. In Maven:';mQ(1140,525,$ec,l5b);mQ(1143,530,_ec,u5b);mQ(1144,1,{},w5b);_.Ee=function x5b(){R1(l$c)};mQ(1145,1,{},z5b);_.Fe=function A5b(a){$wnd.alert(m$c+a)};mQ(1146,1,{},C5b);_.Ge=function D5b(a){$wnd.alert(m$c+a)};mQ(1147,1,{},F5b);mQ(1148,1,{},I5b);_.e=null;mQ(1149,1,Rec,K5b);_.Jb=function L5b(a){$wnd.bootbox.alert(E$c)};mQ(1150,1,Rec,N5b);_.Jb=function O5b(a){Qcc(E$c,new w5b)};mQ(1151,1,Rec,Q5b);_.Jb=function R5b(a){Rcc(E$c,new z5b)};mQ(1152,1,Rec,T5b);_.Jb=function U5b(a){Scc(E$c,new C5b)};mQ(1153,1,{},X5b);var W5b=null;mQ(1154,1,{},$5b);_.a=false;mQ(1193,1,sfc);_.vb=function b8b(){sfb(this.b,N7b(this.a.a))};var dM=kib(Epc,G$c,1140),pM=kib(Epc,H$c,1143),eM=kib(Epc,I$c,1144),fM=kib(Epc,J$c,1145),gM=kib(Epc,K$c,1146),oM=kib(Epc,L$c,1147),lM=kib(Epc,M$c,1148),hM=kib(Epc,N$c,1149),iM=kib(Epc,O$c,1150),jM=kib(Epc,P$c,1151),kM=kib(Epc,Q$c,1152),nM=kib(Epc,R$c,1153),mM=kib(Epc,S$c,1154);wfc(ji)(29);