function Jnb(){}
function KY(a,b){d4(a.c,b)}
function I0(a,b){HY(a.b,b)}
function HY(a,b){P3(a.b,new H_(b))}
function ynb(a,b,c){wM.call(this,a,b,c,(Lkb(),Kkb))}
function a_(a){FY.call(this);this.s=a;this.s[uKb]=PKb}
function b_(){a_.call(this,$doc.createElement(NJb));this.s[uKb]=PKb}
function Z$(){BH(this,$doc.createElement(OKb));this.s[uKb]='divider'}
function d_(){BH(this,$doc.createElement(OKb));this.s[uKb]='dropdown-header'}
function Bsb(a){var b;if(!a.w){b=new Hnb(new Jnb);a.w=b}return a.w}
function Asb(a){var b;if(!a.v){b=new ynb(EL(aN(a.b)),Bsb(a),zsb(a));WL((bN(a.b),b),mN(bN(a.b)));a.v=b}return a.v}
function Hnb(){var a,b,c,d,e,f,g,i,j,k,n,o,p,q,r,s,t,u;QM(this,(a=new x2,EY(a,(b=new B1,b.b=HLb,A1(b),b)),EY(a,(c=new D1,EY(c,(d=new L1,K1(d,(g=new y_(3),Pg(g.s,zNb),g)),d)),EY(c,(e=new G1,EY(e,(i=new b_,EY(i,(j=new LY,R3(j.b,'Click to toggle dropdown'),KY(j,(Vjb(),Tjb)),j)),EY(i,(k=new h_,EY(k,(n=new d_,Pg(n.s,'Header 1'),n)),EY(k,(o=new J0,JY(o.b,'Action 1'),o)),EY(k,(p=new J0,JY(p.b,'Action 2'),I0(p,(chb(),Fab)),p)),EY(k,new Z$),EY(k,(q=new d_,Pg(q.s,'Header 2'),q)),EY(k,(r=new J0,JY(r.b,'Action 3'),I0(r,ybb),Q3(r.b.b),r)),EY(k,(s=new J0,JY(s.b,'Action 4 (disabled)'),GH(s.s,VNb,true),s)),k)),i)),e)),EY(c,(f=new I1,EY(f,(t=new o2,n2(t,(u=new wS,u.b.b+='&lt;b:DropDown&gt;\\n \\s\\s&lt;b:Anchor toggle="DROPDOWN"&gt;Click to toggle dropdown&lt;/b:Anchor&gt;\\n \\s\\s&lt;b:DropDownMenu&gt;\\n \\s\\s\\s\\s&lt;b:DropDownHeader&gt;Header 1&lt;/b:DropDownHeader&gt;\\n \\s\\s\\s\\s&lt;b:ListItem&gt;Action 1&lt;/b:ListItem&gt;\\n \\s\\s\\s\\s&lt;b:ListItem icon="CAMERA"&gt;Action 2&lt;/b:ListItem&gt;\\n \\s\\s\\s\\s&lt;b:Divider/&gt;\\n \\s\\s\\s\\s&lt;b:DropDownHeader&gt;Header 2&lt;/b:DropDownHeader&gt;\\n \\s\\s\\s\\s&lt;b:ListItem icon="CREDIT_CARD" iconPosition="RIGHT"&gt;Action 3&lt;/b:ListItem&gt;\\n \\s\\s\\s\\s&lt;b:ListItem enabled="false"&gt;Action 4 (disabled)&lt;/b:ListItem&gt;\\n \\s\\s&lt;/b:DropDownMenu&gt;\\n &lt;/b:DropDown&gt;',new RD(u.b.b)).b),GH(t.s,CNb,true),GH(t.s,DNb,true),t)),f)),c)),a))}
oD(402,199,uIb,Z$);oD(404,365,vIb);oD(403,404,vIb,b_);oD(405,199,uIb,d_);oD(591,248,AIb,ynb);oD(594,253,BIb,Hnb);oD(595,1,{},Jnb);oD(740,1,TIb);_.tb=function Cvb(){FO(this.c,Asb(this.b.b))};var _v=rR(GMb,'DropdownPresenter',591),bw=rR(GMb,'DropdownView',594),aw=rR(GMb,'DropdownView_BinderImpl',595),Xt=rR(lNb,'AbstractDropDown',404),Cs=rR(oNb,'DropDown',403),As=rR(oNb,'DropDownHeader',405),zs=rR(oNb,'Divider',402);XIb(ye)(6);