function r8b(){}
function p8b(){$mb(this,t8b(new u8b))}
function g8b(a,b,c){Gmb.call(this,a,b,c,(U0b(),T0b))}
function Xac(a){var b;if(!a.eb){b=new p8b(new r8b);a.eb=b}return a.eb}
function v8b(a){var b;b=new xtb;Io(b.a,DKc);rtb(b,h0(a));Io(b.a,EKc);return new O_(b.a.a)}
function w8b(a){var b;b=new xtb;Io(b.a,DKc);rtb(b,h0(a));Io(b.a,EKc);return new O_(b.a.a)}
function u8b(){this.c=Hr($doc);this.a=Hr($doc);this.d=new M1(this.c);this.b=new M1(this.a)}
function Wac(a){var b;if(!a.db){b=new g8b(Plb(lnb(a.a)),Xac(a),Vac(a));fmb((mnb(a.a),b),xnb(mnb(a.a)));a.db=b}return a.db}
function t8b(a){var b,c,d,e,f,g,i,j,k,n,o,p,q,r,s,t,u,v,w;b=new dIb;NAb(b,(c=new ADb(wKc),NAb(c,(d=new QGb,d.a=IIc,PGb(d),d)),NAb(c,(e=new gHb,NAb(e,(f=new sHb(v8b(a.a).a),g=O1((zab(),f.cb)),L1(a.b),g.b?Fq(g.b,g.a,g.c):R1(g.a),rHb(f,(i=new xEb(3),i.b=xKc,vEb(i),i),L1(a.b)),f)),NAb(e,(j=new jHb,NAb(j,(k=new gHb,NAb(k,(n=new sHb(w8b(a.c).a),o=O1(n.cb),L1(a.d),o.b?Fq(o.b,o.a,o.c):R1(o.a),rHb(n,(p=new xEb(3),p.b='Panel Header',vEb(p),p),L1(a.d)),n)),NAb(k,(q=new jHb,NAb(q,(r=new BBb,tr(r.cb,'Panel Body'),r)),q)),NAb(k,(s=new nHb,NAb(s,(t=new BBb,tr(t.cb,'Panel Footer'),t)),s)),k)),j)),NAb(e,(u=new nHb,NAb(u,(v=new byc,WHb(v,(w=new xtb,Io(w.a,'&lt;b:Panel&gt;\\n \\s\\s&lt;b:PanelHeader&gt;\\n \\s\\s\\s\\s&lt;b:Heading size="3" text="..."/&gt;\\n \\s\\s&lt;/b:PanelHeader&gt;\\n \\s\\s&lt;b:PanelBody&gt;\\n \\s\\s\\s\\s&lt;b:Bold text="..."/&gt;\\n \\s\\s&lt;/b:PanelBody&gt;\\n \\s\\s&lt;b:PanelFooter&gt;\\n \\s\\s\\s\\s&lt;b:Bold text="..."/&gt;\\n \\s\\s&lt;/b:PanelFooter&gt;\\n &lt;/b:Panel&gt;\\n'),new O_(w.a.a)).a),p2(v.cb,AKc,true),v)),u)),e)),c));return b}
E$(1009,535,NEc,g8b);E$(1012,540,OEc,p8b);E$(1013,1,{},r8b);E$(1014,1,{},u8b);E$(1058,1,nFc);_.Ab=function pcc(){Qob(this.b,Wac(this.a.a))};var VQ=Krb(AJc,'PanelPresenter',1009),YQ=Krb(AJc,'PanelView',1012),XQ=Krb(AJc,'PanelView_BinderImpl',1013),WQ=Krb(AJc,'PanelView_BinderImpl$Widgets',1014);uFc(dn)(17);