function o$b(){}
function d$b(a,b,c){Ihb.call(this,a,b,c,(pXb(),oXb))}
function Lyb(a){Kvb.call(this);this.ab=a;this.ab[bsc]=_sc}
function Myb(){Lyb.call(this,$doc.createElement(Krc));this.ab[bsc]=_sc}
function Iyb(){KZ(this,$doc.createElement($sc));this.ab[bsc]='divider'}
function Oyb(){KZ(this,$doc.createElement($sc));this.ab[bsc]='dropdown-header'}
function h3b(a){var b;if(!a.w){b=new m$b(new o$b);a.w=b}return a.w}
function g3b(a){var b;if(!a.v){b=new d$b(Rgb(mib(a.b)),h3b(a),f3b(a));hhb((nib(a.b),b),yib(nib(a.b)));a.v=b}return a.v}
function m$b(){var a,b,c,d,e,f,g,i,j,k,n,o,p,q,r,s,t,u,v,w;aib(this,(a=new FCb,Jvb(a,(b=new oyb(Vvc),Jvb(b,(c=new ABb,c.b=Vtc,zBb(c),c)),Jvb(b,(d=new IBb,Jvb(d,(e=new UBb,TBb(e,(f=new jzb(3),bDb(f.d,Wvc),f)),e)),Jvb(d,(g=new LBb,Jvb(g,(i=new Myb,Jvb(i,(j=new Tvb,Mvb(j,(k=new oob,k.b.b+='Click to toggle dropdown',new wX(k.b.b)).b),Svb(j,(zWb(),wWb)),j)),Jvb(i,(n=new Syb,Jvb(n,(o=new Oyb,Qq(o.ab,'Header 1'),o)),Jvb(n,(p=new GAb,Rvb(p.b,'Action 1'),p)),Jvb(n,(q=new GAb,Rvb(q.b,'Action 2'),EAb(q,(TSb(),uMb)),q)),Jvb(n,new Iyb),Jvb(n,(r=new Oyb,Qq(r.ab,'Header 2'),r)),Jvb(n,(s=new GAb,Rvb(s.b,'Action 3'),EAb(s,nNb),IEb(s.b.b),JEb(s.b.b),s)),Jvb(n,(t=new GAb,Rvb(t.b,'Action 4 (disabled)'),TZ(t.ab,uwc,true),t)),n)),i)),g)),Jvb(d,(u=new PBb,Jvb(u,(v=new kmc,wCb(v,(w=new oob,w.b.b+='&lt;b:DropDown&gt;\\n \\s\\s&lt;b:Anchor toggle="DROPDOWN"&gt;Click to toggle dropdown&lt;/b:Anchor&gt;\\n \\s\\s&lt;b:DropDownMenu&gt;\\n \\s\\s\\s\\s&lt;b:DropDownHeader&gt;Header 1&lt;/b:DropDownHeader&gt;\\n \\s\\s\\s\\s&lt;b:ListItem&gt;Action 1&lt;/b:ListItem&gt;\\n \\s\\s\\s\\s&lt;b:ListItem icon="CAMERA"&gt;Action 2&lt;/b:ListItem&gt;\\n \\s\\s\\s\\s&lt;b:Divider/&gt;\\n \\s\\s\\s\\s&lt;b:DropDownHeader&gt;Header 2&lt;/b:DropDownHeader&gt;\\n \\s\\s\\s\\s&lt;b:ListItem icon="CREDIT_CARD" iconPosition="RIGHT" iconSpin="true"&gt;Action 3&lt;/b:ListItem&gt;\\n \\s\\s\\s\\s&lt;b:ListItem enabled="false"&gt;Action 4 (disabled)&lt;/b:ListItem&gt;\\n \\s\\s&lt;/b:DropDownMenu&gt;\\n &lt;/b:DropDown&gt;',new wX(w.b.b)).b),TZ(v.ab,Zvc,true),v)),u)),d)),b)),a))}
sW(695,316,vqc,Iyb);sW(697,654,mqc);sW(696,697,mqc,Myb);sW(698,316,{28:1,33:1,51:1,55:1,56:1,60:1,64:1,65:1,122:1},Oyb);sW(906,522,aqc,d$b);sW(909,527,bqc,m$b);sW(910,1,{},o$b);sW(1056,1,Eqc);_.Ab=function i6b(){Rjb(this.c,g3b(this.b.b))};var hN=Jmb(_uc,'DropdownPresenter',906),jN=Jmb(_uc,'DropdownView',909),iN=Jmb(_uc,'DropdownView_BinderImpl',910),WK=Jmb(Dvc,'AbstractDropDown',697),oJ=Jmb(Gvc,'DropDown',696),mJ=Jmb(Gvc,'DropDownHeader',698),lJ=Jmb(Gvc,'Divider',695);Jqc(Hm)(6);